version: '3'

services:
  app:
    build: ./
    container_name: 'school-app'
    environment:
      - 'APPLICATION_PORT=8081'
    ports:
      - '8081:8081'
    restart: 'on-failure'
    networks:
      - 'school'

networks:
  school:
    external:
      name: 'school'